apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
  namespace: gr1lzy-labs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - image: gr1lzy/homework:latest
          imagePullPolicy: IfNotPresent
          name: devops
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: "/"
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
        - image: nginx:alpine
          name: nginx-reverse-proxy
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/nginx
              readOnly: true
              name: nginx-conf
            - mountPath: /var/log/nginx
              name: log
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: log
          emptyDir: { }
