apiVersion: v1
kind: Service
metadata:
  name: k8s-deployment
  namespace: gr1lzy-labs
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30128
  selector:
    app: devops
